### ISSUE TITLE
Feature request: wrap existing TCP connection

### ISSUE THREAD

**Issue by hoelzro** [sergot/io-socket-ssl#5]
Hello!

I see that this module supports establishing new SSL connections over TCP, but with the module I'm working on right now, I need to be able to take an existing TCP connection and upgrade it to an SSL one.

**Comment by retupmoca** [comment]
This is now doable:

    my $ssl-socket = IO::Socket::SSL.new(:client-socket($plain-socket));

**Comment by sergot** [comment]
done here: https://github.com/sergot/io-socket-ssl/commit/75e66e62581fe87439ef83adacbc47776be15c73

:)

**Comment by hoelzro** [comment]
Awesome, thanks @retupmoca and @sergot!
